### ISSUE TITLE
[Bug]: Compiler errors about Property 'asyncDispose' does not exist on type 'SymbolConstructor' after updating playwright/test to 1.40

### ISSUE THREAD

**Issue by francedot** [microsoft/playwright#31148]
### Version

Bumping from 1.37 or 1.39 to 1.40

### Steps to reproduce

Bumping to any version after 1.40+, we are facing the following TS errors at build:

```
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:4714:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:4714:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:8740:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:8740:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:9006:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:9006:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:13775:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:13775:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:14836:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:14836:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  ...22 lines omitted...
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:14973:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15912:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15912:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15984:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15984:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16581:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16581:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16639:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16639:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
Error: Encountered TypeScript errors

Operations failed.
```

### Expected behavior

Successful bump.

### Actual behavior

```
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:4714:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:4714:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:8740:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:8740:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:9006:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:9006:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:13775:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:13775:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:14836:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
[typescript] Error: common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:14836:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  ...22 lines omitted...
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:14973:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15912:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15912:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15984:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:15984:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16581:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16581:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16639:3 - (TS1169) A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [typescript] common/temp/node_modules/.pnpm/playwright-core@1.40.1/node_modules/playwright-core/types/types.d.ts:16639:11 - (TS2339) Property 'asyncDispose' does not exist on type 'SymbolConstructor'.
Error: Encountered TypeScript errors

Operations failed.
```

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 41.93 GB / 63.95 GB
  Binaries:
    Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.0 - Q:\.tools\.npm-global\pnpm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\<//>\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by francedot** [comment]
Typescript version: 4.7.4

tconfig.json:
```json 
{
  "compilerOptions": {
    "moduleResolution": "node16",
    "module": "esnext",
    "target": "es2018",
    "lib": ["dom", "esnext"],
    "types": ["node"],
    "sourceMap": true,
    "declaration": true,
    "declarationMap": true,
    "removeComments": false,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "preserveConstEnums": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    // "preserveSymlinks": true,
    "traceResolution": false,
    // "noEmitOnError": true,
    "noImplicitOverride": true,
    "useUnknownInCatchVariables": true,
    "strict": true,
    "esModuleInterop": true,
    "stripInternal": true
  },
  "exclude": []
}
```

**Comment by mxschmitt** [comment]
We recommend upgrading to TypeScript v5 and having a recent "@types/node" package, could you try after updating them?

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by Lancer521** [comment]
I am running into this same issue with the exact same output, so I did as advised and updated to latest Typescript and latest `@types/node`. Unfortunately it does not change the outcome at all.

Pertinent versions - confirmed in lock file - are as follows:

```
@types/node: 22.2.0
typescript: 5.5.4
@playwright/test: 1.46.0
```

Any further suggestions?
