### ISSUE TITLE
Property expect().X(for ex: 'toEqual') does not exist on type 'MakeMatchers<void, number>'.

### ISSUE THREAD

**Issue by oa-bcbs** [microsoft/playwright#27158]
### System info
- Playwright Version: ^1.31.2
- Operating System: Windows 11 Enterprise
- Browser: Chromium
- Other info:
"@playwright/test": "^1.31.2",
"typescript": "^5.0.2"

###Description
I'm using playwright with typescript. Once I removed package-lock.json (for pipeline needs) and installed packages back(by npm i). 
I started to see assertion errors such as: Property 'toEqual' does not exist on type 'MakeMatchers<void, number>'.
Seems like assertion types are not included or was not installed as a part of it. What types should I install?
![image](https://github.com/microsoft/playwright/assets/144924260/7c18a90d-260f-4a10-b5a9-5a5e790e8d64)

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    { name: 'setup', testMatch: /.*\.setup\.ts/ },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
  ]
});
```

**Steps**
- install playwright with typescript 
- write a test
- remove package-lock.json and node_modules
- install packages back and open your test.
You should see type errors in your test if eslint in on

**Comment by dgozman** [comment]
@oa-bcbs Could you share a bit more from your test file? It is important for us to know what type does `claims` have.

**Comment by oa-bcbs** [comment]
It can be any object instead of `claim`, type of the object doesn't matter. interesting part is, I can see only following options for assertion 
![image](https://github.com/microsoft/playwright/assets/144924260/b176ddae-e705-45a0-aa43-cc0aa15c45e3)

 
Exact versions from npm ls:
├── @playwright/test@1.38.0
├── @types/mssql@8.1.2
├── @typescript-eslint/eslint-plugin@5.62.0
├── @typescript-eslint/parser@5.62.0
├── cross-env@7.0.3
├── dotenv@16.3.1
├── eslint-config-airbnb-base@15.0.0
├── eslint-config-airbnb-typescript@17.1.0
├── eslint-config-prettier@8.10.0
├── eslint-plugin-import@2.28.1
├── eslint-plugin-prettier@4.2.1
├── eslint@8.49.0
├── prettier@2.8.8
└── typescript@5.2.2

**Comment by dgozman** [comment]
@oa-bcbs This is expected for `respBody` which is probably of the type `APIResponse`. That's why I am asking for specific types. If you could provide a repro that we can run locally, that would also help a lot.

**Comment by oa-bcbs** [comment]
Forgot to mention, I'm doing only API tests. Here's the example:

```
import { test, expect } from '@playwright/test';

export interface IClaimsRes {
  claimCount: number;
  pageLoad: number;
  pageOffset: number;
  claimList: IClaim[];
}

export interface IClaim {
  claimId: string;
  claimType: string;
  claimStatus: string;
  }
  
  test.describe("Example", () => {

    test("test case", async ({request, }) => {
         // Arrange
         const url = buildUrl.claims('list');
         const payload = getClaimsPayload();
         
         // Act
        const resp = await request.post(url, payload);
        const respBody: IClaimsRes = await resp.json();
        const claims: IClaim[] =  respBody.claimList;
        
        // Assert
        expect(claims.length).toBeGreaterThanOrEqual(1);   // Property 'toBeGreaterThanOrEqual' does not exist on type 'MakeMatchers<void, number>'.ts(2339)
        expect(respBody.pageLoad).toEqual(10);  // Property 'toEqual' does not exist on type 'MakeMatchers<void, number>'.ts(2339)

    } )
})
```

Note: I'm working on reproduction

**Comment by dgozman** [comment]
@oa-bcbs I tried to reproduce with the snippet above, and everything works for me with `typescript@5.0.2`, `typescript@5.2.2`, `@playwright/test@1.38.0`, `@playwright/test@1.37.1` and `@playwright/test@1.31.1`.

**Comment by TamalikaChakraborty** [comment]
I'm also getting a similar error **Property 'toBeGreaterThanOrEqual' does not exist on type 'MakeMatchers<void, number>'.** after upgraded playwright/test version to 1.38.0

**Comment by dgozman** [comment]
@TamalikaChakraborty Could you please share a repro with us?

**Comment by oa-bcbs** [comment]
Updates: Restarting the VS Code resolved the issue.
