### ISSUE TITLE
qase.io reporter is not working with playwright 1.22 and 1.23

### ISSUE THREAD

**Issue by NataliaKlepik** [microsoft/playwright#15167]
**Context:**
- GOOD Playwright Version: 1.21.*
- BAD Playwright Version: >1.22.*
- Operating System: Windows
- Extra: "typescript": "~4.3.5", 
 "playwright-qase-reporter": "^1.1.3",
"nodejs": "v17.8.0",
"npm": "8.5.5"

**Describe the bug**

Error: Cannot find module 'chalk'
Require stack:
\node_modules\playwright-qase-reporter\dist\index.js
\node_modules\@playwright\test\lib\loader.js
\node_modules\@playwright\test\lib\runner.js
\node_modules\@playwright\test\lib\cli.js
\node_modules\playwright-core\lib\cli\cli.js
\node_modules\playwright-core\cli.js
\node_modules\@playwright\test\cli.js

**Comment by rwoll** [comment]
Thanks for the report. This looks like an issue with qase's package and dependencies (and they have a [fix](https://github.com/qase-tms/qase-javascript/pull/210)—although maybe unreleased at this point): https://github.com/qase-tms/qase-javascript/issues/207

Please raise an issue there in the qase repo.

**As a work around, you could likely try manually installing and declaring a dep on `chalk` (via `npm i chalk@^4.1.0`)** on behalf of the qase package.
