### ISSUE TITLE
Can't run tests in debug mode

### ISSUE THREAD

**Issue by marianamelo1** [microsoft/playwright#30829]
Type: <b>Bug</b>

Everytime that I go to the testing extension and I click to debug the test, the test loads forever and never starts. 

Extension version: 1.1.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (13.55GB free)|
|Process Argv|--crash-reporter-id 21febb57-4dba-4466-93a7-9f4ac1d1ca26|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vstes516:30244333
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvptcf:31043158
a69g1124:31046351
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by emilchalcedony** [comment]
Facing the same issue after upgrading to V1.1.1.
Downgraded to 1.0.22 and able to debug!

**Comment by emilchalcedony** [comment]
Facing the same issue after upgrading to V1.1.1.

**Comment by vl4d1m1r4** [comment]
I also face this issue, this is the error in the developer console:

``` 
ERR [Extension Host] TypeError: o.includes is not a function
    at Roe (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:117:346)
    at pp.launchProgram (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:115:9563)
    at n (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:115:4131)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ap.launch (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:113:31785)
    at jI.captureLaunch (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:130:11414)
    at jI._launch (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:130:11161)
    at async Promise.all (index 3)
    at jI._boot (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:130:10285)
    at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:130:9214
    at mu._onMessage (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:47:4835)
```

Node version: 21.7.1

However, my colleague, with the exact same setup of node, vscode version, extension version and os version, is able to debug the tests.

**Comment by mxschmitt** [comment]
Please retry in v1.1.3 which we just released.

**Comment by emilchalcedony** [comment]
> Please retry in v1.1.3 which we just released.

Not working with V1.1.3 & 1.1.4

**Comment by mxschmitt** [comment]
@emilchalcedony could you please provide us your repository structure as a git repository? Does it happen with a [newly created project](https://playwright.dev/docs/intro)?

**Comment by emilchalcedony** [comment]
> @emilchalcedony could you please provide us your repository structure as a git repository? Does it happen with a [newly created project](https://playwright.dev/docs/intro)?

![image](https://github.com/microsoft/playwright/assets/52150533/f5578370-618b-4d1e-9e51-a2ef08290ce6)

it was working fine with V1.0.23. Facing this issue after upgrading to v1.1.1 +

**Comment by emilchalcedony** [comment]
it was working fine with V1.0.23. Facing this issue after upgrading to v1.1.1 +

**Comment by pavelfeldman** [comment]
@emilchalcedony what's you extension version?

**Comment by mxschmitt** [comment]
Fixed in https://github.com/microsoft/playwright-vscode/pull/485.

(Feel free to try the beta via https://github.com/microsoft/playwright-vscode/wiki)

**Comment by mbouchardC3** [comment]
I confirm it does work with 1.1.5 when I also have the latest playwright/test! Thank you!
