### PR TITLE
browser(webkit): restore default a11y settings

### PR DESCRIPTION
**Pull request by dpino**
This PR removes the mock classes that were introduced to allow buidling with ENABLE_ACCESSIBILITY enabled but USE_ATSPI and USE_ATK disabled. Upstream should allow building with ENABLE_ACCESSIBILITY disabled, although at the moment the mock classes were introduced there were build errors that prevented using this option. Changes:

  * [Restore default A11y settings](https://github.com/dpino/webkit/commit/8e825492fd4743bb4351472fd9de9863c0da22c1)
  * [Remove code that allow to build with ENABLE_ACCESSIBILTY=1 but ATSPI=0](https://github.com/dpino/webkit/commit/c3893bffde7850232204fa54217e36a08ee0dfbe)

### CODE REVIEW

**Comment by yury-s** [comment]
I believe the issue was that we wanted our accessibility tests to pass while the implementation (ATK or ATSPI) caused compilation errors on one of the platforms. Passing the tests (page-accessibility.spec.ts) if I remember correctly requires ENABLE_ACCESSIBILITY=1

**Comment by dpino** [comment]
OK, I was not aware of `page-accessibility.spec.ts`, I thought A11y was not needed for Playwright tests.

I think the issue was, besides some build errors in the A11y code path that were later fixed upstream, Ubuntu 18.04 lacked the ATSPI dependecy llibraries and the ATK code path, which Ubuntu 18.04 was still using, was removed upstream. The ATSPI dependency was added later in the [jhbuild-minimal.modules](https://github.com/WebKit/WebKit/blob/main/Tools/jhbuild/jhbuild-minimal.modules#L16).

I modified the patch to restore the default settings and build with ENABLE_ACCESSIBILITY=1 and ATPSI. The build works in Ubuntu 18.04 and `page-accessibility.spec.ts` passes:

```
> playwright-internal@1.25.0-next wtest
> playwright test --config=tests/library/playwright.config.ts --project=webkit "tests/page/page-accessibility.spec.ts"

Using executable at /home/dpino/playwright/browser_patches/webkit/checkout/WebKitBuild/bundle/pw_run.sh

Running 19 tests using 16 workers

  2 skipped
  17 passed (1s)
```

**Comment by dpino** [comment]
Moved to draft as there were build errors in Ubuntu 20.04.

**Comment by dpino** [comment]
Pretty diff patches:

* [Restore default A11y settings](https://github.com/dpino/webkit/commit/8e825492fd4743bb4351472fd9de9863c0da22c1)
* [Remove code that allow to build with ENABLE_ACCESSIBILTY=1 but ATSPI=0](https://github.com/dpino/webkit/commit/c3893bffde7850232204fa54217e36a08ee0dfbe)

**Review by yury-s — APPROVED** [review]
We also discussed this in a meeting and decided to deprecate the accessibility snapshots (https://github.com/microsoft/playwright/issues/16159) and remove the implementation in a few releases. At that point we should be able to compile with ENABLE_ACCESSIBLITY=0.
