### ISSUE TITLE
[Bug]:     Error: page.goto: net::ERR_ABORTED; maybe frame was detached?

### ISSUE THREAD

**Issue by aykutde96** [microsoft/playwright#34889]
### Version

1.50.1

### Steps to reproduce

Some users have experienced similar problems in the examples below, but no solution has been suggested. If there is a solution for this, can you share it?

https://github.com/microsoft/playwright/issues/18137
https://github.com/microsoft/playwright/issues/8145 
https://github.com/microsoft/playwright/issues/28364
https://github.com/microsoft/playwright/issues/22759

The automation I created consists of projects with different baseUrls and when I run them in parallel, sometimes I encounter the error below, sometimes I don't

Error: page.goto: net::ERR_ABORTED; maybe frame was detached? 
Call log:
  - navigating to 

### Expected behavior

should navigate to url successfully 

### Actual behavior

give a white screen with this error
Error: page.goto: net::ERR_ABORTED; maybe frame was detached? 
Call log:
  - navigating to 

### Environment

```shell
node version: v20.11.1
pw version: 1.50.1
OS: MacOs
```

I've used pnpm for the package manager

**Comment by aykutde96** [comment]
Browser is stuck in about:blank couldn't navigate the proper url 
<img width="1256" alt="Image" src="https://github.com/user-attachments/assets/3f06efde-9710-4a65-9dc9-a5b7e13d8698" />

**Comment by aykutde96** [comment]
I've just found the problem but I don't know the solution please help. This problem only occured when I've added  addCookies step before page.goto

```
test.beforeEach(
  async ({
    page,
    context,
  }) => {
    await context.addCookies([
      { name: "testCookie", value: "test", domain: ".test.com", path: "/" },
    ]);
    await page.goto("");
  },
);
test("test1", { tag: "@All" }, async ({ page }) => {
  await expect(page).toHaveTitle(/Title/);
});

```

**Comment by aykutde96** [comment]
Thank you for your response. Since the project belongs to my workplace, I can't share it, but I will prepare a simplified version and share it tomorrow.

**Comment by aykutde96** [comment]
Hello @yury-s, thank you for your response again, but I couldn't reproduce the issue this time. I'm closing the issue. If I can reproduce it again, I'll come back with a ready repo. Thanks for your support!

**Comment by astemirboziev** [comment]
Same issue I'm facing at work. I'm trying to update playwright from 1.37 to 1.50 (Python client) and I see a lot of error like this. All methods like expect_nagivation, wait_for_url and so on are failing with this:
```
failed on setup with "playwright._impl._errors.Error: Page.reload: net::ERR_ABORTED; maybe frame was detached?
Call log:
  - waiting for navigation until "load""
```

**Comment by dagnelies-elo** [comment]
Same issue here. Interestingly, in my case this error only occurs with chromium, but not with firefox. At some point, even trivial tests  fail with that error. The test that fail look more like an effect than a cause. Also, in IntelliJ, it does not seem to stop properly the test suite, like if some connection is still open. Perhaps these are some hints at the problem.

**Comment by ariannemlopez** [comment]
I just installed playwright on mac. I got the same issue on chromium and firefox when running the default tests from the installation. I did npx playwright uninstall --all && npx playwright install but nothing happened.

**Comment by RajNalluri** [comment]
Still seeing this issue

**Comment by mjgerace** [comment]
> Hello [@yury-s](https://github.com/yury-s), thank you for your response again, but I couldn't reproduce the issue this time. I'm closing the issue. If I can reproduce it again, I'll come back with a ready repo. Thanks for your support!

I am also hitting this issue, can we reopen this?

**Comment by aykutde96** [comment]
I haven't encountered this error again. However, since others have experienced it, I reopened the issue.

**Comment by mjgerace** [comment]
> I haven't encountered this error again. However, since others have experienced it, I reopened the issue.

Is there any debugging info I can provide that would help provide clarity on this? I am happy to help in any way I can

**Comment by RajNalluri** [comment]
In my case, I realized that this error occurs when i MISS adding 'await' before page.goto() and also when i forget adding 'await' before 'test.step'
i.e., below code throws the current error as I have missing 'await' before test.step
```
test.step('Step 1', async () => {
    await page.goto('https://www.saucedemo.com/v1/')
  })
```

**Comment by dgozman** [comment]
@mjgerace Could you please file a new issue by filling in the "Bug Report" template and providing a repro? It is almost impossible to make progress when many people have different setups but arrive to the same error message, and noone has a clear reproducible. Thank you!

**Comment by RuxinZ** [comment]
> I've just found the problem but I don't know the solution please help. This problem only occured when I've added addCookies step before page.goto
> 
> ```
> test.beforeEach(
>   async ({
>     page,
>     context,
>   }) => {
>     await context.addCookies([
>       { name: "testCookie", value: "test", domain: ".test.com", path: "/" },
>     ]);
>     await page.goto("");
>   },
> );
> test("test1", { tag: "@All" }, async ({ page }) => {
>   await expect(page).toHaveTitle(/Title/);
> });
> ```

@aykutde96 I encountered the same error in a similar case when awaiting page reload after accessing the context.
```
  test('Verify some cookie settings', async ({
    page,
  }) => {

    await page.goto(URL_TO_BE_TESTED)

    // Get initial UID
    const initialCookies = await page.context().cookies()
    const initialUid = initialCookies.find(
      (cookie) => cookie.name === UID_COOKIE,
    )?.value

    await page.reload({ waitUntil: 'load', timeout: 3000 })
});

```
Error: page.reload: net::ERR_ABORTED; maybe frame was detached?

When I comment out the code for getting initial UID, page reload works fine. I tried adjusting the options argument to wait until different states, but none worked.

**Comment by Stephen100Mwangi** [comment]
I am also experiencing this issue. Apparently, the test was failing for missing "await".

`test("Page Fixture - Playwright test", async ({ page }) => {
  // Visit URLs without having to declare browser and context
 await page.goto("https://demo.playwright.dev/todomvc/#/");
});`

Alternatively, you could use the browser fixture. Initialize a new context for every test then create a new page (fresh). This way the new context is treated as a new "incognito window" and the new page is opened afresh

`test("First test", async ({ browser }) => {
  // Browser and page are fixtures
  // Playwright fixtures MUST be wrapped in `{}`
  // Fixtures are global variables available across your project

   // Start a new instance - Think of it like a new Incognito mode
  // We can pass parameters to the newContext method as proxy
  const context = await browser.newContext();
  // Next we need to open a new page
  const page = await context.newPage();
  // Visit URLs
  page.goto("https://demo.playwright.dev/todomvc/#/");
});`

**Comment by ry-sny** [comment]
I'm also hitting this issue with the python sync library.

On version:
```
playwright==1.54.0
Mac OS 15.1 (24B83)
```

I see it after calling page.goto(<url>) to a url that has been visited by previous tests. The only workaround I've found is to create a new context and page for each test. 

```
self = <playwright._impl._connection.Connection object at 0x115499150>
cb = <function Channel.send.<locals>.<lambda> at 0x11574a660>
is_internal = False, title = None

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(
            task, "__pw_stack__", None
        ) or inspect.stack(0)
    
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.goto: net::ERR_ABORTED at <URL>
E           Call log:
E             - navigating to "<URL>", waiting until "load"
../../../venv/lib/python3.11/site-packages/playwright/_impl/_connection.py:558: Error
```

UPDATE:

I was able to work around this issue by calling `page.wait_for_load_state("networkidle")` before calling `page.goto`

**Comment by dmeehan1968** [comment]
This also seems to occur if the server has not started (or fails before the request arrives or in handling the request).  In my case my server has a bit of startup overhead, I was creating an instance of the server as part of the beforeAll sequence but it was failing, so the first page.goto was then getting an error.

**Comment by marianoOca** [comment]
*UPDATE* fix? So I committed the following which happened to fix all the issues I had. Which seems contraintuitive at first... and it is, I guess I'll just let GPT delirate a good explanation of why this works. The fix, in my case, was adding the webServer to playwright config instead of booting up the front end on my own, waiting for it and then running the test on that. What I added to `playwright.config.ts` is:

```
export default defineConfig({
...
  webServer: {
    command: "████████", //my front end boot up command
    url: "http://localhost:3000",
    timeout: 45_000,
    reuseExistingServer: !process.env.CI,
  },
...
});
```

I hope that helps!!

*from before*

Same issue over here. Mine appears when scaling my test suite, adding more tests (moving from 80 to 170ish), causes the following errors apparently randomly on tests that used to work as expected, and work fine on their own. Another detail is that this occurs on git CI, everything works fine locally.

```
Test timeout of 20000ms exceeded.
Error: page.goto: net::ERR_ABORTED; maybe frame was detached?
Call log:
  - navigating to "http://localhost:3000/", waiting until "domcontentloaded"

  4 | test.describe("██████", () => {
  5 |   test("█████████████", async ({ page }) => {
> 6 |     await page.goto("/", { waitUntil: "domcontentloaded" });
    |                ^
  7 |     const stcPage = new STCUnregisteredPage(page);
  8 |
  9 |     await stcPage.navigateToJobs();
    at ████████████████████████████████
```

and many of these too:

```
Test timeout of 20000ms exceeded while running "beforeEach" hook.

  17 |
  18 | test.describe("██████", () => {
> 19 |   test.beforeEach(async ({ page }) => {
     |        ^
  20 |     await page.goto("/██", { waitUntil: "domcontentloaded" });
  21 |   });
  22 |
    at ████████████████████████████████
```

**Comment by tkikala** [comment]
For me it gets reproduced occasionally with following steps:

```
    await productSelectionPage.page.goBack({ waitUntil: "domcontentloaded" });
    await productSelectionPage.page.goForward();
```
