### ISSUE TITLE
[Bug]: Playwright with 'jest-extended' matchers error

### ISSUE THREAD

**Issue by andrii-nastenko** [microsoft/playwright#31595]
### Version

1.45.0

### Steps to reproduce

preconditions:

Install packages:

1) "@playwright/test": "1.45.0"
2) "jest-extended": "4.0.2"

Create and apply following files into your project:

matchers.ts

```
import * as JestExtendedMatchersMethods from 'jest-extended';

expect.extend(JestExtendedMatchersMethods.default);

export {expect};
```

matchers-types.d.ts

```
declare global {
  namespace PlaywrightTest {
    interface Matchers<R, T> extends jest.Matchers<R> {}
  }
}

export {};
```

use jest matcher in some test, e.g. 

`expect(someArray).toIncludeAllMembers([1,2,3,4,5]);`

### Expected behavior

Matcher should work and pass check

### Actual behavior

TypeError: equals is not a function

### Additional context

**Important thing:** 

Matchers from 'jest-extended' package has always worked with previous PW versions (e.g. it worked with previous 1.44.1). 
The problem appeared stating with 1.45.0 version.

### Environment

```shell
packages:

"@playwright/test": "1.45.0"
"jest-extended": "4.0.2"

OS: macos sonoma 14.4.1

Package manager: yarn 1.22.21

Node: v18.12.0
```

**Comment by mxschmitt** [comment]
Investigation:

- We miss `this.equals()` here: https://github.com/microsoft/playwright/blob/00131c1e3fb9c524b2b2b4496ebebcabf46b326e/packages/playwright/src/matchers/expect.ts#L135-L141
- Jest supports it as per here: https://jestjs.io/docs/expect#thisequalsa-b-customtesters

**Comment by mxschmitt** [comment]
Playwright Expect is not the same as Jest Expect, see [here](https://playwright.dev/docs/test-assertions#add-custom-matchers-using-expectextend:~:text=Do%20not%20confuse%20Playwright%27s%20expect%20with%20the%20expect%20library.).

**Comment by dgozman** [comment]
Capturing offline discussion: introduce `equals()` method that will throw a nice message pointing to the docs.
