### ISSUE TITLE
[BUG] TypeError after migrating from 1.19 to 1.20

### ISSUE THREAD

**Issue by federico-moretti** [microsoft/playwright#13389]
```
## System:
 - OS: macOS 12.3
 - Memory: 23.93 MB / 16.00 GB
## Binaries:
 - Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
 - npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 ```

I've been using Playwright v1.19.2 without any problem since its release, today I tried to update to the v1.20.2 to use the snapshots mask option and now as I start the tests this error comes out:

```
TypeError: (0 , _strings.searchParamsToString) is not a function
```

`searchParamsToString` is a function that I use in another function that I import inside the test. Everything else in my setup is pretty vanilla, I just use TypeScript in both my app and Playwright.

This error happens if I use `npx playwright tests/e2e/` and also if use `playwright tests/e2e/` inside docker with this image `mcr.microsoft.com/playwright:v1.20.2-focal`.

I looked for changes to the build in the changelog but nothing seemed relevant.

Thank you.

**Comment by mxschmitt** [comment]
Could you share a repro with us? Try to minimise the actual behaviour to a smaller repro, which we can run locally.

**Comment by federico-moretti** [comment]
I found the problem: the file I was importing was a `tsx`, I converted it to `ts` and now it works correctly.

Although I resolved my issue, I think is still a problem that migrating from 1.19 to 1.20 broke `tsx` files.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/13422 for now to track it. I agree that its not expected.
