### PR TITLE
fix(expect): throw unsupported error when using this.equals() in expect

### LINKED ISSUE #31595: [Bug]: Playwright with 'jest-extended' matchers error
### Version

1.45.0

### Steps to reproduce

preconditions:

Install packages:

1) "@playwright/test": "1.45.0"
2) "jest-extended": "4.0.2"

Create and apply following files into your project:

matchers.ts

```
import * as JestExtendedMatchersMethods from 'jest-extended';

expect.extend(JestExtendedMatchersMethods.default);

export {expect};
```

matchers-types.d.ts

```
declare global {
  namespace PlaywrightTest {
    interface Matchers<R, T> extends jest.Matchers<R> {}
  }
}

export {};
```

use jest matcher in some test, e.g. 

`expect(someArray).toIncludeAllMembers([1,2,3,4,5]);`

### Expected behavior

Matcher should work and pass check

### Actual behavior

TypeError: equals is not a function

### Additional context

**Important thing:** 

Matchers from 'jest-extended' package has always worked with previous PW versions (e.g. it worked with previous 1.44.1). 
The problem appeared stating with 1.45.0 version.

### Environment

```shell
packages:

"@playwright/test": "1.45.0"
"jest-extended": "4.0.2"

OS: macos sonoma 14.4.1

Package manager: yarn 1.22.21

Node: v18.12.0
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Closes https://github.com/microsoft/playwright/issues/31595

### CODE REVIEW

File: packages/playwright/src/matchers/expect.ts [hunk 1]
```diff
@@ -183,6 +184,10 @@ function createExpect(info: ExpectMetaInfo) {
   return expectInstance;
 }
 
+function throwUnsupportedExpectMatcherError() {
+  throw new Error('Playwright Expect matchers are not fully compatible with Jest matchers. See https://aka.ms/playwright/expect-compatibility');
```
Comment (dgozman) [inline packages/playwright/src/matchers/expect.ts:188]:
```suggestion
  throw new Error('It looks like you are using custom expect matchers that are not compatible with Playwright. See https://aka.ms/playwright/expect-compatibility');
```

File: docs/src/test-assertions-js.md [hunk 2]
```diff
@@ -308,6 +308,8 @@ test('amount', async () => {
 });
 ```
 
+### Compatibility with expect from Jest
```
Comment (dgozman) [inline docs/src/test-assertions-js.md:311]:
```suggestion
### Compatibility with expect library
```

**Review by dgozman — APPROVED** [review]

**Review by Skn0tt — APPROVED** [review]
