### ISSUE TITLE
[BUG] Getting "Please install @playwright/test package to use Playwright Test."

### ISSUE THREAD

**Issue by thecodrr** [microsoft/playwright#6981]
**Context:**
## System:
 - OS: Linux 5.4 Ubuntu 21.04 (Hirsute Hippo)
 - Memory: 502.32 MB / 15.52 GB
 - Container: Yes
## Binaries:
 - Node: 15.14.0 - ~/.volta/tools/image/node/15.14.0/bin/node
 - Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
 - npm: 7.15.0 - ~/.volta/tools/image/npm/7.15.0/bin/npm
## Languages:
 - Bash: 5.1.4 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.12.0 => 1.12.0

**Describe the bug**

I just installed `playwright` version `1.12` to try out the new test runner but I am consistently getting `Please install @playwright/test package to use Playwright Test.` no matter how many times I do `yarn add --dev @playwright/test`.

**Comment by pavelfeldman** [comment]
You don't need `playwright` when using `@playwright/test`:

```bash
yarn init -y
yarn add --dev @playwright/test
npx playwright test
```

**Comment by cyrilletuzi** [comment]
Had the same issue, because previous beta versions of `@playwright/test` did require `playwright`.

Solution:
- `npm rm playwright`
- `npm install @playwright/test -D`

Then it works.

**Comment by cyrilletuzi** [comment]
Note/question: for projects using Playwright for both unit tests and e2e tests, could this be a problem? or is `@playwright/test`-only the way to go in this scenario?

**Comment by mpuertao** [comment]
In my case, 
- Delete playwright, 
- Install @playwright/test
- Reinstall playwright. 

Success!!!

**Comment by thecodrr** [comment]
> You don't need `playwright` when using `@playwright/test`:
> 
> ```shell
> yarn init -y
> yarn add --dev @playwright/test
> npx playwright test
> ```

Yep. This worked.

**Comment by mariusc23** [comment]
I ran into this issue because I had `test` in my `.yarnclean` file. Yarn removed the `lib/test` folder and the entire `node_modules/@playright/test` folder because of this 🤦 

I fixed by adding this to `.yarnclean`:
```
!@playwright/test/**
```

**Comment by nathanchase** [comment]
I've been trying everything I can think of to get testing to work in an Azure Pipeline.

My YAML:
```
resources:
  containers:
  - container: playwright
    image: mcr.microsoft.com/playwright:focal

  repositories:
  - repository: self
    type: git
    ref: refs/heads/develop

jobs:
- job: e2e_testing
  container: playwright
  displayName: E2E Testing

  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: self

  - script: |
      yarn
      npx playwright test
    displayName: 'Run test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testRunTitle: 'Test Report'
    displayName: 'Publish Reports'
```
but I get... 
```
Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test
##[error]Bash exited with code '1'.
```
If I try to use 'yarn playwright test', then I get...
```
yarn run v1.22.11
$ playwright test
/bin/sh: 1: playwright: not found
error Command failed with exit code 127.
```
What is the magic combination to make this work??

**Comment by mrienstra** [comment]
@nathanchase, does `yarn playwright test` work locally? Might be hard to diagnose without knowing more.

**Comment by nathanchase** [comment]
> @nathanchase, does `yarn playwright test` work locally? Might be hard to diagnose without knowing more.

Yes, works fine locally.

**Comment by mrienstra** [comment]
@nathanchase, stab in the dark, but maybe you need to run `yarn playwright install` in CI?

**Comment by nathanchase** [comment]
> @nathanchase, stab in the dark, but maybe you need to run `yarn playwright install` in CI?

Well, that's why I was using their Docker container, since it's supposed to have all that stuff preinstalled and ready to go. I tried manually installing everything and not using the container, and still had the same result.

I just need to find someone that actually has a working Azure DevOps .yaml for Playwright. I've come across some that are for Windows/.NET, but nothing for Linux/Node based projects.

**Comment by viveleroi** [comment]
I'm running into this as well, yarn 3.2.4 on Windows 11. I installed playwright for the first time using `yarn create playwright`. `npx playwright test` was giving me this error. Trying `yarn playwright test` instead throws a different error:

```
PS C:\Users\mbotsko\Desktop\Emprise\sammweb-v3> yarn playwright test
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\mbotsko\Desktop\v3\.yarn\cache\@playwright-test-npm-1.27.1-ebcb7fdc03-92f219a78c.zip\node_modules\@playwright\test\lib\experimentalLoader.js' imported from C:\Users\mbotsko\Desktop\v3\
Did you mean to import C:/Users/mbotsko/Desktop/v3/.yarn/cache/@playwright-test-npm-1.27.1-ebcb7fdc03-92f219a78c.zip/node_modules/@playwright/test/lib/experimentalLoader.js?
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:305:11)
    at moduleResolve (node:internal/modules/esm/resolve:866:10)
    at defaultResolve (node:internal/modules/esm/resolve:1074:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:425:18)
    at ESMLoader.import (node:internal/modules/esm/loader:522:22)
    at initializeLoader (node:internal/process/esm_loader:75:58)
    at loadESM (node:internal/process/esm_loader:90:11) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.9.
```

**Comment by pereorga** [comment]
For anybody experiencing this after upgrading to 1.34.0 (I am), I think this may be related to https://github.com/microsoft/playwright/issues/23098

**Comment by dman777** [comment]
I am getting this issue only in Azure pipelines. And I don't have playwright installed

```json
   "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
      "@playwright/test": "^1.34.3",
      "chai": "^4.3.7"
    },
    "dependencies": {
      "nodemon": "^2.0.22"
    }
  }
```

**Comment by warorc** [comment]
> You don't need `playwright` when using `@playwright/test`:
> 
> ```shell
> yarn init -y
> yarn add --dev @playwright/test
> npx playwright test
> ```

Why I can't use both. In our project we use monorepo. And one of application in this monorepo uses crawlee: https://www.npmjs.com/package/crawlee

where in dependencies it use playwright. So now we have to choose should we test out product, or use one of our critical application. And it means that we need to use cypress instead of playwright for testing or other framework.

**Comment by jasonk** [comment]
If anyone else ends up here looking for a solution. The root cause of this problem is that the `playwright` package and the `@playwright/test` package both provide a cli tool named `playwright`. The one in the `playwright` package just throws this error if you attempt to run `playwright test` or something else.

If you have both packages installed then whether `playwright test` works or not depends entirely on what order they were installed in. If `playwright` was installed last then it won't work, if `@playwright/test` was installed last then it will work.

If you need to have both installed, the only way I've found to work around this is to install [postinstall-postinstall](https://github.com/ds300/postinstall-postinstall#readme) and add a `postinstall` script that does this:
```
cd node_modules/.bin
ln -sf ../@playwright/test/cli.js playwright
```
This will force the symlink to the package to be replaced with the `@playwright/test` version every time you run `npm install` (or `yarn install`, or whatever).

**Comment by utkarshkukreti** [comment]
@jasonk thanks for the pointer! I used a different workaround - pass the full path to cli.js in package.json's `scripts.test`:

```diff
-    "test": "playwright test",
+    "test": "node_modules/@playwright/test/cli.js test",
```

**Comment by ksandin** [comment]
> > You don't need `playwright` when using `@playwright/test`:
> > ```shell
> > yarn init -y
> > yarn add --dev @playwright/test
> > npx playwright test
> > ```
> 
> Why I can't use both. In our project we use monorepo. And one of application in this monorepo uses crawlee: https://www.npmjs.com/package/crawlee
> 
> where in dependencies it use playwright. So now we have to choose should we test out product, or use one of our critical application. And it means that we need to use cypress instead of playwright for testing or other framework.

I'm also using a monorepo facing this exact issue. With monorepos becoming increasingly popular I think this problem really needs a better solution. Even without a monorepo, it's entirely possible that you have a project that has a different dependency that installs `playwright` under the hood, meaning you can't remove `playwright` to fix this unless you remove the dependency that is using it.

**Comment by alexn-s** [comment]
i just encountered this issue. it really is problematic and counter intuitive that both packages have the same cli name and conflict.
i think the best way forward (altough it breaks a lot of package.json script and ci pipelines) to change the name of the playwright test script and resolve the conflict. it is quite shame but i probably use puppeteer again. there are multiple use case for testing and automation in one "project". would love to use playwright again in the future

**Comment by yordan-kanchelov** [comment]
with the attempt to migrate to pnpm i started reproducing this issue as well

**Comment by Shruthi-DN** [comment]
> Had the same issue, because previous beta versions of `@playwright/test` did require `playwright`.
> 
> Solution:
> 
> * `npm rm playwright`
> * `npm install @playwright/test -D`
> 
> Then it works.

Thank you! I just had to explicitly install @playwright/test in the github workflow yml. This error was bothering as it didn't happen in my local runs. I didn't have to remove playwright. Not sure if/where that package is installed.

**Comment by sturoid** [comment]
Reproducing this issue using pnpm.

**Comment by andersekdahl** [comment]
I had this issue in a repo using npm workspaces. `npx playwright install` gave a `not found` error when run in the root. When I changed to run it inside the workspace package that needed playwright instead it worked fine.

**Comment by zhkostadinov** [comment]
Hey, team
The issue is still there:
`Require stack:
- /demo/node_modules/playwright/lib/common/config.js
- /demo/node_modules/playwright/lib/reporters/json.js
- /demo/node_modules/playwright/lib/runner/reporters.js
- /demo/node_modules/playwright/lib/runner/runner.js
- /demo/node_modules/playwright/lib/program.js
- /demo/node_modules/@playwright/test/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at /demo/node_modules/playwright/lib/common/config.js:205:21
    at Array.map (<anonymous>)
    at resolveReporters (/home/kosta/Desktop/52Entertainment/demo/node_modules/playwright/lib/common/config.js:203:110)
    at new FullConfigInternal (/demo/node_modules/playwright/lib/common/config.js:77:56)
    at loadConfig (/demo/node_modules/playwright/lib/common/configLoader.js:103:22)
    at loadConfigFromFileRestartIfNeeded (/demo/node_modules/playwright/lib/common/configLoader.js:258:10)
    at runTests (/demo/node_modules/playwright/lib/program.js:192:18)
    at t.<anonymous> (/demo/node_modules/playwright/lib/program.js:54:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'demo/node_modules/playwright/lib/common/config.js',
    '/node_modules/playwright/lib/reporters/json.js',
    '/demo/node_modules/playwright/lib/runner/reporters.js',
    '/demo/node_modules/playwright/lib/runner/runner.js',
    '/demo/node_modules/playwright/lib/program.js',
    '/demo/node_modules/@playwright/test/cli.js'
  ]
}
`
