### PR TITLE
devops: fix Firefox build on Ubuntu 22.04 arm64

### PR DESCRIPTION
**Pull request by aslushnikov**
Turns out the weird compilation error is fixed if we use Clang 14
to compile.

This is the same clang that would've been shipped in mozilla build
toolchain.

### CODE REVIEW

**Review by mxschmitt — APPROVED** [review]

**Comment by Mone71** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
