### ISSUE TITLE
[BUG] TypeError when importing with ts paths in >=1.20

### ISSUE THREAD

**Issue by damevi** [microsoft/playwright#13793]
**Context:**
- Playwright Version: ^1.20
- Operating System: MacOS
- Node.js version: 16.14.2
- Browser: All

**Describe the bug**

Hello, starting with Playwright version 1.20, I am getting an error when importing a function using ts paths and barrel imports. This works fine in 1.19 and below. 

Importing a function throws an error
```
TypeError: (0 , _RandomString.randomString) is not a function
```

Please see https://github.com/damevi/playwright-ts-paths-error for reproducible repo with ts config that resembles my project's ts config

Can you please point me if this is related to some breaking changes and can be somehow fixed via config or is this a regression?

Kind regards,
damevi

**Comment by pavelfeldman** [comment]
Playwright does not support TSX files, renaming RandomString.tsx to RandomString.ts would fix it.

**Comment by batmaid-uciek** [comment]
@pavelfeldman how come it works in Playwright 1.19 then?

**Comment by damevi** [comment]
@pavelfeldman thanks for the quick answer but how come it works in Playwright 1.19 then?

**Comment by pavelfeldman** [comment]
We were less strict in 1.19 and it was fixed.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by damevi** [comment]
@pavelfeldman wasn't tsx support added in https://github.com/microsoft/playwright/issues/7121 though? have you now reverted this?
