### PR TITLE
browser(webkit): rebase to 08/11/22 (253363@main)

### PR DESCRIPTION
**Pull request by dpino**
Changes:

  - [chore(webkit): bootstrap build 1699](https://github.com/dpino/webkit/commit/26efd4b0b8ca5f27b52510cbc1389555363a36a3) 
  - [[GLIB] Build fix, add missing header 'SpeechSynthesisErrorCode.h'](https://github.com/dpino/webkit/commit/6dc414c55c46da25201dd28a739a83714eeae359)
  - [[WPE] Cannot build with USE_SYSTEM_MALLOC enabled](https://github.com/dpino/webkit/commit/6bf8e0216297b88301cd1893de4ae98ae6abbe20)
    - Pushed upstream: https://github.com/WebKit/WebKit/pull/3257
  - [Revert downstream change to avoid linking error in Ubuntu 18.04](https://github.com/dpino/webkit/commit/38f74dd49a49709597da3ca0e44a8eee53162f87)
  - [[macOS] Unreviewed, fix non-unified build errors](https://github.com/dpino/webkit/commit/539679df5fa6aba3bc4fb9dedfcfd142ea824bbb)
    - Pushed upstream: https://github.com/WebKit/WebKit/pull/3211 
 
Also changes build.sh to build with USE_SYSTEM_MALLOC in Ubuntu 18.04. This avoids the linking error in Ubuntu 18.04. The patch from last week doesn't longer work because it was meant for GCC8 and now Ubuntu 18.04 uses GCC9.

Some notest about installing GCC9 in Ubuntu 18.04:

```bash
# Run as root.

$ apt install software-properties-common
$ add-apt-repository ppa:ubuntu-toolchain-r/test
$ apt update
$ apt install gcc-9
$ apt install g++-9
$ update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 --slave /usr/bin/g++ g++ /usr/bin/g++-9
$ update-alternatives --config gcc
There are 3 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path            Priority   Status
--------------------
* 0            /usr/bin/gcc-9   900       auto mode
  1            /usr/bin/gcc-7   700       manual mode
  2            /usr/bin/gcc-8   800       manual mode
  3            /usr/bin/gcc-9   900       manual mode

Press <enter> to keep the current choice[*], or type selection number: 
```

Besides these changes there were some other minor fixes that already landed upstream:
  * [[GLIB] Unreviewed, build fix for Ubuntu LTS/Debian after 253304@main](https://github.com/WebKit/WebKit/pull/3214)
  * [[JHBuild] Fix runtime error in 'update-webkit-libs-jhbuild'](https://github.com/WebKit/WebKit/pull/3213)

### CODE REVIEW

**Comment by dpino** [comment]
I need to update this PR. I removed too much code when I reverted the patch from last week and compilation failed in Mac and Ubuntu 20.04.

File: browser_patches/webkit/build.sh [hunk 1]
```diff
@@ -19,6 +32,9 @@ build_gtk() {
     --cmakeargs=-DENABLE_INTROSPECTION=OFF
     --cmakeargs=-DUSE_GSTREAMER_WEBRTC=FALSE
   )
+  if is_ubuntu_18_04; then
```
Comment (aslushnikov) [inline browser_patches/webkit/build.sh:35]:
```suggestion
  if is_linux ubuntu 18.04; then
```

**Review by yury-s — APPROVED** [review]

File: browser_patches/webkit/build.sh [hunk 2]
```diff
@@ -42,6 +58,9 @@ build_wpe() {
     --cmakeargs=-DENABLE_WEBXR=OFF
     --cmakeargs=-DUSE_GSTREAMER_WEBRTC=FALSE
   )
+  if is_ubuntu_18_04; then
```
Comment (aslushnikov) [inline browser_patches/webkit/build.sh:61]:
```suggestion
  if is_linux ubuntu 18.04; then
```
