### ISSUE TITLE
[BUG] page.is_visible not auto wait element display

### ISSUE THREAD

**Issue by Olaking1** [microsoft/playwright#8246]
**Context:**
- Playwright Version: 1.13.0
- Operating System: Mac
- Browser:All
- python 3.8.5

**Code Snippet**

```python
from playwright.sync_api import Playwright, sync_playwright

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://github.com/login")
    page.fill("input[name=\"login\"]", "1624351@gmail.com")
    page.fill("input[name=\"password\"]", "1234567")
    page.click("input:has-text(\"Sign in\")")
    is_visible = page.is_visible("text=Incorrect username or password123.")
    assert is_visible == True
    context.close()
    browser.close()
with sync_playwright() as playwright:
    run(playwright)
```

**Describe the bug**
```python
is_visible = page.is_visible("text=Incorrect username or password123.")
```
hope to auto wait 30 seconds and returns is_visible=False
but now, it returns False immediately without auto wait
It runs well on version 1.8a.1, but when I upgrade to 1.13.0，is_visible cannot auto wait

**Comment by vsravuri** [comment]
You can try page.isVisible instead of page.is_visible

page.isVisible(selector[, options])

**Comment by Olaking1** [comment]
> isVisible

**Comment by Olaking1** [comment]
Seems 'Page' object has no attribute 'isVisible'

**Comment by mxschmitt** [comment]
In Python its called is_visible(), see here: https://playwright.dev/python/docs/api/class-page#page-is-visible

**Comment by Olaking1** [comment]
> In Python its called is_visible(), see here: https://playwright.dev/python/docs/api/class-page#page-is-visible

Yep, but it does't auto wait

**Comment by JoelEinbinder** [comment]
`is_visible` checks if the element is visible *right now*. It does not wait for that element to become visibile. To wait for the element to become visible, use [`wait_for_selector`](https://playwright.dev/python/docs/api/class-frame#frame-wait-for-selector)

**Comment by pavelfeldman** [comment]
We've updated the docs to reflect this information now. Thanks!
