### ISSUE TITLE
[BUG] Fail to import from typescript files in package type module

### ISSUE THREAD

**Issue by GenrikhFetischev** [microsoft/playwright#14053]
**Context:**
- Playwright Version: 1.22.0-alpha-may-10-2022
- Operating System: MacOS
- Node.js version: v17.9.0
- Browser: Not applicable

**Describe the bug**

There is a problem with importing from Typescript files with `"type": "module"` in the `package.json` file.
When I try to import something to a test file, I get the following error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/playwright-bug/test/testDependency' imported from    ####/playwright-bug/test/test.test.ts

```

I've created a repository that represents the configuration of my project and where is possible to reproduce the issue by run the command `pnpm test` - https://github.com/GenrikhFetischev/playwright-bug-report

**Additional info**
When I try to import with a file extension like [there](https://github.com/GenrikhFetischev/playwright-bug-report/blob/main/test/test.test.ts#L3)  import work.
Without `"type": "module"` in `package.json` imports work

**Comment by pierscowburn** [comment]
I also have this problem, in particular since updating from 1.19.1 to 1.21.1.

**Comment by mxschmitt** [comment]
Note: VSCode is showing a warning if its imported with the extension: 
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/17984549/167874241-3ceb782d-eb29-417d-a0da-701e2b5a021c.png">

So we should fix it.

**Comment by pavelfeldman** [comment]
Please refer to https://www.typescriptlang.org/docs/handbook/esm-node.html for interoperability between the TS and ESM. You are missing `.js` in your import.

**Comment by GenrikhFetischev** [comment]
@pavelfeldman  Thanks for pointing to the docs! I haven't known about that implementation, but I agree with the docs' phrase: "This might feel a bit cumbersome". Typescript realization of ESM looks weird because we have to declare `import smth.js` in a `.ts` file to import smth from a `.ts` file. I totally understand that it's not a good idea to go against the language specification, but is there any hope that the Playwright team could not follow that specification? As far as I understood, Playwright uses its own loader and can handle file extensions under the hood without explicit declaration in an import statement.

**Comment by pavelfeldman** [comment]
Going our own way is very likely to cause even more problems. I would rather wait for the TS / ESM story to improve while staying consistent with it.

**Comment by GenrikhFetischev** [comment]
Got it; thanks for your time! So, I'll close the issue on that point
