### ISSUE TITLE
[Bug]: Playwright 1.58.0 collects *.esm.preflight files as tests, causing duplicate test title errors

### ISSUE THREAD

**Issue by Abhinegi2** [microsoft/playwright#39172]
### Version

1.58.0

### Steps to reproduce

**Minimal Reproduction Repository:** https://github.com/Abhinegi2/playwright-issue

Clone the repository and run:
```bash
git clone https://github.com/Abhinegi2/playwright-issue.git
cd playwright-issue
npm install
npx playwright install chromium
npx playwright test
```
Or reproduce from scratch:

1. Create a TypeScript ESM project with "type": "module" in package.json.
2. Install @playwright/test@1.58.0 and tsx@4.21.0
3. import tsx/esm in [playwright.config.ts]
``` 
import { defineConfig } from "@playwright/test";
import "tsx/esm";
export default defineConfig({
testDir: "./tests",
build: { external: ["*"] },
}); 
```
4. Create any test file (e.g., tests/example.spec.ts)
5. Run npx playwright test

### Expected behavior

Playwright should only collect and execute tests from `*.spec.ts` files (or other configured test file patterns). No `*.esm.preflight` files should be involved in test collection.

### Actual behavior

Playwright reports duplicate test title errors, referencing non-existent `*.esm.preflight` files:
Error: duplicate test title "example test", first declared in example.spec.ts.esm.preflight:3
at example.spec.ts:1
```
1 | import { test, expect } from "@playwright/test";
| ^
2 |
3 | test("example test", async ({ page }) => {
4 | await page.goto("[https://example.com](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)");
```

These `.esm.preflight` files don't exist in the repository but appear to be created by the `tsx/esm` loader and are being incorrectly collected as test files by Playwright.

### Additional context

- **Regression**: This works correctly in Playwright 1.57.0
- **Workaround**: Downgrade to `@playwright/test@1.57.0`
- **Real-world impact**: This is blocking upgrades in production projects, such as [Aam-Digital/ndb-core](https://github.com/Aam-Digital/ndb-core)
- **Related issue**: #39028 (closed, requesting proper repro - this is the proper reproduction)

The `.esm.preflight` files appear to be generated by tsx's ESM loader transformation but should be excluded from Playwright's test file collection pattern.

### Environment

```shell
System:
    OS: macOS 26.2
    CPU: (8) arm64 Apple M3
    Memory: 92.39 MB / 8.00 GB
Binaries:
    Node: 22.19.0
    npm: 11.6.4
IDEs:
    VSCode: 1.108.2
Languages:
    Bash: 3.2.57
npmPackages:
    @playwright/test: 1.58.0
```

**Comment by Skn0tt** [comment]
Thanks for providing the repro. Things start working when I remove the `build: { external: ['*'] }` line from the config. Can you elaborate on why you need `tsx` installed? Playwright performs its own TypeScript transpilation.

**Comment by Abhinegi2** [comment]
Thanks for following up. We validated this in our original [repo](https://github.com/Aam-Digital/ndb-core) and can confirm `tsx` is required for us right now.

Our matrix:
1. `import "tsx/esm"` + `build: { external: ["*"] }` -  works (`playwright test --list` finds all tests)
2. remove `tsx/esm`, keep `build.external` -   fails with unresolved ESM imports like:
   `Cannot find module .../e2e/fixtures.js`
3. keep `tsx/esm`, remove `build.external` -   Playwright transform path fails on our app TS syntax, e.g.:
   `TypeScript 'declare' fields must first be transformed ...` (from a decorated model file)

So in our case:
- `build.external` is used to stop Playwright from transforming the app/e2e import graph.
- `tsx/esm` is used as the runtime ESM TS loader for our `.js` import specifiers pointing to TS sources and decorator-heavy TS files.

If Playwright can support this combination natively (ESM `.js` specifiers -> TS sources + decorators/declare fields) without `tsx`, we’re happy to switch.

**Comment by Skn0tt** [comment]
Could you update the reproduction case to capture what you need `tsx/esm` for? I took a cursory look at your repo but it's hard to identify the gist of what's happening with this issue.

**Comment by Abhinegi2** [comment]
I've updated the reproduction repository to demonstrate why tsx/esm is needed.

**Updated repository:** https://github.com/Abhinegi2/playwright-issue

### added:

1. `e2e/fixtures.ts` - Shared TypeScript file with experimental decorators (in the original repo It's the central test setup file that provides shared utilities, fixtures, and configuration for all Playwright tests in your project. )
2. `tsconfig.json` - ESM configuration with `experimentalDecorators` enabled
3. `tests/example.spec.ts` - Updated to import using `.js` extension pointing to `.ts` file:
   ```typescript
   import { createTestData } from "../e2e/fixtures.js"; // Points to fixtures.ts

### Testing the need for tsx/esm:
You can verify why tsx/esm is necessary by commenting out line 3 in playwright.config.ts:
```
import { defineConfig } from "@playwright/test";
// import "tsx/esm";  // <-- comment this out

export default defineConfig({
  testDir: "./tests",
  build: { external: ["*"] },
});
```
Then run: `npx playwright test`

Result without tsx/esm: `Error: Cannot find module '.../e2e/fixtures.js'`
Result with tsx/esm (original config): `Error: duplicate test title "example test", first declared in example.spec.ts.esm.preflight:3`

This demonstrates that tsx/esm is required to resolve .js imports to .ts files in ESM TypeScript projects, but causes the duplicate test bug in Playwright 1.58.0.

**Comment by Skn0tt** [comment]
When I comment out both `tsx/esm` and `build`, everything works:

```diff
diff --git a/playwright.config.ts b/playwright.config.ts
index ffabffd..29d2467 100644
--- a/playwright.config.ts
+++ b/playwright.config.ts
@@ -1,7 +1,5 @@
 import { defineConfig } from "@playwright/test";
-import "tsx/esm";
 
 export default defineConfig({
   testDir: "./tests",
-  build: { external: ["*"] },
 });
```

```ts
❯ npx playwright clear-cache && npx playwright test
Removing /private/var/folders/g0/6cfmrv7j7ls58c3f9gp04qfh0000gn/T/playwright-transform-cache-501

Running 2 tests using 1 worker

  ✓  1 tests/example.spec.ts:5:1 › example test (622ms)
  ✓  2 tests/example.spec.ts:13:1 › another test (436ms)

  2 passed (2.0s)
```

But `fixtures.ts` also doesn't contain any experimental decorators. Did you forget to add something? I'm on commit `3c89547e2eaaa21fafd5a6f598c1e3980e24555e`.

**Comment by Abhinegi2** [comment]
You're  right - thank you for testing! I've updated the reproduction to better demonstrate why `build.external` is necessary.

I've added TypeScript `declare` fields to `e2e/fixtures.ts`:
```typescript
export class ExampleEntity {
  declare id: string;  // Not supported by Playwright's default transformer
  declare name: string;
  
  constructor(id: string, name: string) {
    this.id = id;
    this.name = name;
  }
```

**Testing different configurations:**
1. With tsx/esm + build.external (current config): `error-Duplicate test title errors (the bug)`
2. Without both (your suggestion and Remove tsx/esm import and build.external): `error: TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript `
3. Without tsx/esm only (keep build.external): Result: Cannot resolve .js imports to .ts files

This shows that we need both tsx/esm (for ESM .js→.ts resolution) and build.external (for TypeScript features Playwright can't transform), but this combination triggers the bug in 1.58.0. (latest commit -2efc14e7a51d35b1e77b899e626f5180fc70ee92)

**Comment by Skn0tt** [comment]
That particular case is already tracked in https://github.com/microsoft/playwright/issues/38586. Is `declare` what's causing the problems in your real project, or is it a different syntax?

**Comment by Abhinegi2** [comment]
Yes, `declare` fields are what's causing the issue in our real project. We have multiple model classes using them,
So the issue is:

1. We need build.external because of these declare fields (tracked in #38586)
2. We need tsx/esm to handle ESM .js → .ts import resolution
3. But combining both in Playwright 1.58.0 causes the .esm.preflight duplicate test bug (regression from 1.57.0)

The .esm.preflight bug (#39172) is separate from the declare fields support (#38586). Even if #38586 gets fixed and Playwright can handle declare fields, we'd still need tsx/esm for the ESM import resolution, which would still trigger this .esm.preflight bug in 1.58.0.

**Comment by Skn0tt** [comment]
I see, thanks. I understand the issue better now. I was able to narrow down the regression to https://github.com/microsoft/playwright/commit/ad994617f26ed19932eefe4ae94650fb17f2124e, and can see how https://github.com/microsoft/playwright/pull/39177 fixes it. I'm unsure whether we want to accomodate for external bundling in that way though, are loaders are bespoke. We'll discuss it with the team.

**Comment by Abhinegi2** [comment]
Thanks for looking into this. Please let us know the decision after discussing it with the team

**Comment by Skn0tt** [comment]
Node.js loaders are designed to be composable, so we should work with `tsx/esm`. We spotted a bug in our preflight mechanism, i'll take a stab at fixing it later today.
